// `loci spec` — emit the CLI spec as JSON or markdown.
//
// JSON: machine-readable contract consumed by tests and tooling.
// Markdown: site-ready doc suitable for docs/CLI_SPEC_v0.1.md.
//
// Usage:
//   loci spec                             (JSON to stdout)
//   loci spec --format markdown           (markdown to stdout)
//   loci spec --format markdown --out docs/CLI_SPEC_v0.1.md

import { writeFileSync } from "fs"
import { CLI_SPEC, type CliSpec, type CommandSpec, type FlagSpec, type EnvVarSpec } from "../spec.ts"

export async function cmdSpec(args: string[]): Promise<void> {
  const format = flag(args, "--format") ?? "json"
  const outFile = flag(args, "--out")

  let output: string
  switch (format) {
    case "json":
      output = JSON.stringify(CLI_SPEC, null, 2)
      break
    case "markdown":
      output = renderSpecMarkdown(CLI_SPEC)
      break
    default:
      console.error(`Unknown format: ${format}. Use: json, markdown`)
      process.exit(1)
  }

  if (outFile) {
    writeFileSync(outFile, output + "\n")
    console.log(`Spec written to: ${outFile}`)
  } else {
    console.log(output)
  }
}

export function renderSpecMarkdown(spec: CliSpec): string {
  const lines: string[] = []

  lines.push(`# ${spec.name} CLI Spec v${spec.version}`)
  lines.push(``)
  lines.push(spec.description)
  lines.push(``)
  lines.push(`> Auto-generated by \`loci spec --format markdown\`. Edit \`cli/src/spec.ts\` to update.`)
  lines.push(``)

  lines.push(`## Global Flags`)
  lines.push(``)
  for (const f of spec.globals) lines.push(renderFlag(f))
  lines.push(``)

  lines.push(`## Environment Variables`)
  lines.push(``)
  for (const e of spec.env) lines.push(...renderEnvVar(e))

  lines.push(`## Commands`)
  lines.push(``)
  for (const cmd of spec.commands) lines.push(...renderCommand(cmd, "##"))

  return lines.join("\n")
}

function renderEnvVar(e: EnvVarSpec): string[] {
  const lines: string[] = []
  lines.push(`### \`${e.name}\``)
  lines.push(``)
  lines.push(e.description)
  lines.push(``)
  if (e.example) lines.push(`- Example: \`${e.example}\``)
  if (e.setBy) lines.push(`- Set by: \`${e.setBy}\``)
  lines.push(``)
  return lines
}

function renderCommand(cmd: CommandSpec, level: string): string[] {
  const lines: string[] = []

  const aliases = cmd.aliases && cmd.aliases.length > 0
    ? ` *(aliases: ${cmd.aliases.join(", ")})*`
    : ""
  const delegateSuffix = cmd.delegate
    ? ` — *delegates to native binary*`
    : ""

  lines.push(`${level}# \`${cmd.name}\`${aliases}${delegateSuffix}`)
  lines.push(``)
  lines.push(cmd.description)
  lines.push(``)

  if (cmd.args && cmd.args.length > 0) {
    lines.push(`**Arguments:**`)
    lines.push(``)
    for (const a of cmd.args) {
      const req = a.required ? "*(required)*" : "*(optional)*"
      lines.push(`- \`<${a.name}>\` ${req} — ${a.description}`)
    }
    lines.push(``)
  }

  if (cmd.flags && cmd.flags.length > 0) {
    lines.push(`**Flags:**`)
    lines.push(``)
    for (const f of cmd.flags) lines.push(renderFlag(f))
    lines.push(``)
  }

  if (cmd.examples && cmd.examples.length > 0) {
    lines.push(`**Examples:**`)
    lines.push(``)
    lines.push("```sh")
    for (const ex of cmd.examples) lines.push(ex)
    lines.push("```")
    lines.push(``)
  }

  if (cmd.subcommands && cmd.subcommands.length > 0) {
    for (const sub of cmd.subcommands) {
      lines.push(...renderCommand(sub, level + "#"))
    }
  }

  return lines
}

function renderFlag(f: FlagSpec): string {
  let namePart: string
  if (f.type === "boolean") {
    namePart = `\`${f.name}\``
  } else if (f.type === "enum" && f.enum) {
    namePart = `\`${f.name} <${f.enum.join("|")}>\``
  } else {
    namePart = `\`${f.name} <${f.type}>\``
  }

  const parts = [`- ${namePart}`, f.description]
  if (f.default !== undefined) parts.push(`(default: \`${f.default}\`)`)
  if (f.envVar) parts.push(`(env: \`${f.envVar}\`)`)
  if (f.required) parts.push(`*(required)*`)

  return parts.join(" — ")
}

function flag(args: string[], name: string): string | null {
  const i = args.indexOf(name)
  return i >= 0 && i + 1 < args.length ? args[i + 1] : null
}
